### PR TITLE
Add config.yaml for Kasari et al 2019 to example-datasets/fungi/saccharomyces

### PR DESCRIPTION
**Pull request by swinterbourne**
Add Kasari_2019_eEF3-depleted_RPF_4-samples_CDS_w_250utrs_config.yaml to example-datasets/fungi/saccharomyces. Related to issue #48

### CODE REVIEW

**Review by FlicAnderson — COMMENTED** [review]
Hiya, same comment for this dataset as the others to keep them all consistent: see [here](https://github.com/riboviz/example-datasets/pull/64#issuecomment-786618114)

But in this one I think it's worth removing the `noUMIs` folder part from the `dir_*` paths because ideally once we've got this quality-controlled & are certain it's correct, we should know whether it has UMIs or not.  Again, we're aiming to keep the whole set of datasets nice and consistent in structure.

**Comment by FlicAnderson** [comment]
Currently running this on Eddie to check.

**Comment by FlicAnderson** [comment]
> Currently running this on Eddie to check.

Sadly this run failed due to lack of memory. I've added more & set it to re-run. I ought to have used resume, but I forgot, and it would be good to know how it runs in one go, so I suppose it's not the end of the world. 

```
Job 11389845 (K-Sc-eEF3_2019) Aborted
 Exit Status      = 137
 Signal           = KILL
 User             = fanders6
 Queue            = eddie@node3g10.ecdf.ed.ac.uk
 Host             = node3g10.ecdf.ed.ac.uk
 Start Time       = 04/21/2021 14:47:30.999
 End Time         = 04/21/2021 20:38:55.150
 CPU              = 2:01:37:00
 Max vmem         = 181.017G
 Max rss          = NA
failed execd enforced h_vmem limit because:
job 11389845.1 died through signal KILL (9)
``` 
This was initially with `-pe sharedmem 9` & `h_vmem=20G` which would've given 180GB, which was exceeded during the generateStatsFigs part of the pipeline.  I'm re-running with `-pe sharedmem 12` which should give it 240GB to play with.  

Will update when it's complete.

**Comment by FlicAnderson** [comment]
Weirdly, re-running this with the 240GB ran to completion, but it only required 170GB at the maximum. 
```
Job 11399859 (K-Sc-eEF3_2019) Complete
 User             = fanders6
 Queue            = eddie@node3g10.ecdf.ed.ac.uk
 Host             = node3g10.ecdf.ed.ac.uk
 Start Time       = 04/22/2021 12:03:43.859
 End Time         = 04/23/2021 00:38:42.915
 User Time        = 1:21:08:11
 System Time      = 1:07:14:23
 Wallclock Time   = 12:34:59
 CPU              = 3:04:22:35
 Max vmem         = 170.847G
 Max rss          = NA
 Exit Status      = 0
``` 
It generates about 11GB worth in the `/output` folder.  


Samples: 

S1-N1-eEF3: 

Frame proportion doesn't seem great for this sample, but this replicates [what Sophie found previously]. Proportions of frame 0 and 3 are both ~ 45%.  
[S1-N1-eEF3: 3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/6422260/3ntframe_propbygene.pdf)

The startcodon ribogrid plot also seems to show some weird artifacts with quite a few reads around lengths 21 & 22, and a bit of untidyness at the start of the plot.   
[S1-N1-eEF3: startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6422271/startcodon_ribogrid.pdf)


S2-D1-eEF3: 

Frames are fairly similar across all three here. 
[S2-D1-eEF3: 3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/6422282/3ntframe_propbygene.pdf)

Read lengths - another unexpected bump of reads at length 22, with most reads at length 31, 32 and 33. Not sure this is ideal?
[S2-D1-eEF3: read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6422297/read_lengths.pdf)
[S2-D1-eEF3: startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6422299/startcodon_ribogrid.pdf)


S3-N2-eEF3: 

Frames 0 & 2 have roughly similar proportions again, but no clear leader... 
[S3-N2-eEF3: 3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/6422305/3ntframe_propbygene.pdf) 

Read lengths mainly 31 and 32 followed closely by 30. The length 22 'bump' visible in this sample too. 
[S3-N2-eEF3: read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6422310/read_lengths.pdf) 


S4-D2-eEF3: 

Roughly similar frame proportions again, Frame 3 ahead slightly.
[3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/6422349/3ntframe_propbygene.pdf)

Read lengths for this sample are quite off - peak sitting at length 33. The length 22 reads bump here too. 
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6422365/read_lengths.pdf)

For the startcodon ribogrid plot, the 'noisy start' is quite clear, and there's also a strange bump particularly visible showing reads of length 50. I think something's definitely not right here. 
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6422400/startcodon_ribogrid.pdf)

We're also not seeing much periodicity in the startcodon ribogridbar plot, as the bars sit at pretty much the same height all the way along afte position zero. Only on the bar for length 32 do we see some clearer 3nt periodicity...
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6422406/startcodon_ribogridbar.pdf)

General QC: 
Across all samples, the 3NT periodicity isn't too great - we've got some 'U-shaped' troughs, or upside-down-U-shaped peaks; not especially clean looking plots. (For example sample 3: 
[S3-N2-eEF3 3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6422330/3nt_periodicity.pdf) or sample 4: [S4-D2-eEF3: 3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6422352/3nt_periodicity.pdf) )


I think we still have some issues here, and I'm presuming you found some/most of these earlier @swinterbourne but didn't get a chance to investigate too much further? 

**I'd recommend we spend more time on checking QC & adapters/UMIs are correct for this before merging this dataset.**

**Comment by ewallace** [comment]
I agree that the read-lengths plot having a max round 30/32 nt depending on sample is a sign that something is wrong. We should probably check the adapters first. Then maybe check where the reads are aligned and whether there's a particular pattern of mismatches etc. Will require a little by way of forensics.

**Comment by FlicAnderson** [comment]
I'm closing this pull request for now (NOT MERGED) as this dataset needs further work to confirm what the issues are and to fix those. 

We need to confirm whether the issues are with the configuration setup, rather than being data quality problems. 

I am leaving the branch `Kasari-Sc-2019-config-48` live to avoid losing this work.

**Pull request closed without merging**
