### PR TITLE
Upgrade README.md

### PR DESCRIPTION
**Pull request by ewallace**
Edits to README.md

* describes optional files and a-site annotation better.
* completes "start here" section.
* improved organization
* more information on filenames
* focuses on requirements for putting in a commit.
* better account of .gff files
* reminder to update kingdom README.md

Does not have an issue template. Also does not have

### CODE REVIEW

**Review by swinterbourne — COMMENTED** [review]
Looks good! For line 30 in "Fill in gaps in README.md" It has been changed from "We are planning to add" to "We are working on add", would either "working to add" or "working on adding" be better?

**Comment by 3mma-mack** [comment]
I agree it is very clear. I like the inclusion of different examples and links to documentation where relevant.

I couldn't spot any errors bar the one @swinterbourne has already pointed out.

**Review by 3mma-mack — COMMENTED** [review]
I agree it is very clear. I like the inclusion of different examples and links to documentation where relevant.

I couldn't spot any errors bar the one @swinterbourne has already pointed out.

**Comment by ewallace** [comment]
Thank you! Correcting and merging.

**Pull request merged**
