### PR TITLE
Update kingdom README.md files

### LINKED ISSUE #50: Update kingdom-level README files
Kingdom-level README files could & should reflect the datasets that have been added in the genus-specific directories.

### PR DESCRIPTION
**Pull request by ewallace**
Fixes #50

### CODE REVIEW

**Review by FlicAnderson — APPROVED** [review]
I think that it's consistent now and good to go. Ready to merge & close.

**Comment by ewallace** [comment]
This is great. Don't we need to rename the actual folders as well, though?

**Comment by FlicAnderson** [comment]
@ewallace good point, DONE & updated the file names and yamls etc.

**Comment by ewallace** [comment]
Amazing, thanks! Merging and closing.

**Pull request merged**
