### PR TITLE
Adding Mundodi et al 2021 Candida albicans dataset

### PR DESCRIPTION
**Pull request by acope3**

### CODE REVIEW

**Comment by ewallace** [comment]
@3mma-mack and @swinterbourne  have agreed to review this pull request.

**Review by 3mma-mack — COMMENTED** [review]
I tried running the file and though it does complete successfully, the outputs are rather unusual - ie the 3nt periodicity is messy and there is a wide range of read lengths. I just want to check this was expected?

One minor change I would make is including '.gz' at the end of the fq_files but bar that everything seems good.

37C1
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6799948/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6799949/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6799950/startcodon_ribogridbar.pdf)


37C2
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6799954/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6799955/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6799956/startcodon_ribogridbar.pdf)

37C3
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6799961/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6799962/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6799963/startcodon_ribogridbar.pdf)

**Comment by acope3** [comment]
@3mma-mack I observed something similar with this data. I reran another C. albicans dataset that was previously included by @FlicAnderson that gave much cleaner results, suggesting it's not something specific to C. albicans. It may just be this dataset. It could also be something in the publication I missed.

**Comment by swinterbourne** [comment]
I tried running the file and it failed to complete. For each sample it failed at the GenerateStatsFigs step. 

When I checked the `.command.err` logs they all contained the message `all scheduled cores encountered errors in user code`. I also got an out of memory error message in `hs_err_pid175958.log`. 

This might be caused by insufficient scratch space as we recently received an email about this being an issue. 

Most recent commit:
```
commit 1f1eb2ae1bde47926ff67245a80298cfb535cc15
Author: Mike Jackson <m.jackson@epcc.ed.ac.uk>
Date:   Thu Jun 24 14:53:37 2021 +0100

    Fixed broken link in docs/developer/debugging.md
```

**Comment by swinterbourne** [comment]
The dataset (finally!) completed successfully. I agree with @3mma-mack about including '.gz' at the end of the fq_files. 

Also, should the folder name be changed to M-Ca_2021 to match the style of the other config files? 

37C1
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6905920/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6905922/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6905923/startcodon_ribogridbar.pdf)

37C2
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6905925/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6905928/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6905929/startcodon_ribogridbar.pdf)

37C3
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6905930/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6905931/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6905933/startcodon_ribogridbar.pdf)

**Review by swinterbourne — COMMENTED** [review]
Should the folder name be changed to M-Ca_2021 to match the style of the other config files?

**Comment by acope3** [comment]
@swinterbourne Sure, we can do that. Other than that are we ready to add this dataset?

**Comment by FlicAnderson** [comment]
I've added the null organism-specific params back in (as per [issue #92]).

**Comment by FlicAnderson** [comment]
Made the changes in [@3mma-mack's comment](https://github.com/riboviz/example-datasets/pull/85#issuecomment-889719872); think this is mergeable, so I'm merging & closing this. Nice work @acope3 & reviewers @swinterbourne and @3mma-mack :)

**Pull request merged**
