### PR TITLE
Add new species h capsulatum 91

### PR DESCRIPTION
**Pull request by swinterbourne**

### CODE REVIEW

**Comment by 3mma-mack** [comment]
Looking at the commits, it looks like this branch was made off of the `update-configs-76`, as it seems to also be adding the 2.1 versions of the config files. I'm not sure if this is what we wanted but I don't think it will be too huge a problem as we have previously tested the configs and they all worked

**Comment by FlicAnderson** [comment]
> Looking at the commits, it looks like this branch was made off of the `update-configs-76`, as it seems to also be adding the 2.1 versions of the config files. I'm not sure if this is what we wanted but I don't think it will be too huge a problem as we have previously tested the configs and they all worked

Thanks @3mma-mack - I suspected this was probably the case, but thanks for confirming! -  @swinterbourne, hang off merging until I check what's what in `update-configs-76` and see what the best merge-order is :)

**Comment by FlicAnderson** [comment]
This is still waiting me confirming the files included are fine to merge & I'll get it sorted over the next few days.

This checking also ties into #71 so I need to get cracking following the merge of [riboviz/#417 PR of viz code](https://github.com/riboviz/riboviz/pull/417).

**Review by FlicAnderson — APPROVED** [review]
Good work, some inconsistencies in non-H-capsulatum files, and the contaminants file for H. capsulatum was saved as .fq format rather than the correct .fa format, but this was a quick fix as the file contents were correct, just needed the extension changed.  Think this is good to merge.

**Pull request merged**
