### PR TITLE
Cryptococcus h99 3

### PR DESCRIPTION
**Pull request by FlicAnderson**
These datasets #3 and #4 both run on Eddie currently.  See info : [here for JEC21](https://github.com/riboviz/example-datasets/issues/4#issuecomment-700161127) and [here for H99](https://github.com/riboviz/example-datasets/issues/3#issuecomment-700142160)

Yamls are updated & all commits pushed.

### CODE REVIEW

**Comment by ewallace** [comment]
@FlicAnderson can you send me the job submission script so I can try for myself - I'll just look in to JEC21. Then I can accept, add Neurospora #2, and close.

It looks like I still need to edit the provenance files? Anything else?

**Comment by FlicAnderson** [comment]
Hi Edward, 

This is the content of the submission script:

```
#!/bin/sh
# Grid Engine options (lines prefixed with #$)
#$ -N W-Cn-JEC21_2020              
#$ -cwd                  
#$ -l h_rt=48:00:00 
#$ -l h_vmem=8G 
#$ -pe sharedmem 16
#$ -P bio_wallace_rna_riboviz 
#$ -o $JOB_NAME-$JOB_ID-$HOSTNAME.o
#$ -e $JOB_NAME-$JOB_ID-$HOSTNAME.e
#  These options are:
#  job name: -N
#  use the current working directory: -cwd
#  runtime limit of 48 hours: -l h_rt
#  ask for 8 Gbyte RAM: -l h_vmem
#  use shared memory parallel environment, request 16 CPUs
#  add to priority queue in project bio_wallace_rna_riboviz
#  redirect output with format jobname-jobID-hostname (jobname -N)
#  redirect error with same format as output
# Initialise the environment modules
. /etc/profile.d/modules.sh
 
#!/usr/bin/env bash
export R_LIBS=/exports/csce/eddie/biology/groups/wallace_rna/Rlibrary
module load openmpi
module load igmm/apps/BEDTools 
module load igmm/apps/bowtie
module load igmm/apps/hdf5
module load igmm/apps/HISAT2
module load igmm/apps/pigz
module load igmm/apps/R/3.6.3
module load anaconda
source activate riboviz

DATAFOLDER="Wallace_2020_JEC21"

echo "Running riboviz on dataset: ${DATAFOLDER}"

# move to scratch space
cd /exports/eddie/scratch/$USER

# make folder there
mkdir $DATAFOLDER
mkdir $DATAFOLDER/input

cd $DATAFOLDER/input

echo "${PWD}"

# get the dataset read files
module load igmm/apps/sratoolkit/2.10.8

##prefetch with Aspera client
prefetch SRR9620588 SRR9620586
fasterq-dump SRR9620588
fasterq-dump SRR9620586

# use pigz to zip .fastq files into .fastq.gz files:
pigz *.fastq

echo "hopefully downloaded and pigz'd the files into /exports/eddie/scratch/$USER/${DATAFOLDER}/input"

# presumes downloaded the SRA files OK & they're in /exports/eddie/scratch/$USER/$DATAFOLDER/input

# move to riboviz folder: 
cd $HOME/riboviz/riboviz

echo "moved to $HOME/riboviz/riboviz"

# make system link at riboviz folder to folder on scratch
ln -s /exports/eddie/scratch/$USER/$DATAFOLDER

# copy yaml into the riboviz/$DATAFOLDER folder, rename it
cp $HOME/riboviz/example-datasets/fungi/cryptococcus/Wallace_2020_JEC21_2-samples_10p_up12dwn9_CDS_120bpL_120bpR_config.yaml $DATAFOLDER/Wallace_2020_JEC21_2-samples_10p_up12dwn9_CDS_120bpL_120bpR_config.yaml

# presuming I'm in correct branch on riboviz

# move back up to riboviz folder (or nextflow won't run)
cd $HOME/riboviz/riboviz
echo "now in folder: ${PWD} ready to run"

# presuming .yaml config exists in $HOME/riboviz/riboviz/${DATAFOLDER} AND it points to ${DATAFOLDER}/input for files as required

# run nextflow validation: 
nextflow run prep_riboviz.nf -params-file ${DATAFOLDER}/Wallace_2020_JEC21_2-samples_10p_up12dwn9_CDS_120bpL_120bpR_config.yaml -work-dir ${DATAFOLDER}/work -ansi-log false --validate_only

# run nextflow: 
nextflow run prep_riboviz.nf -params-file ${DATAFOLDER}/Wallace_2020_JEC21_2-samples_10p_up12dwn9_CDS_120bpL_120bpR_config.yaml -work-dir ${DATAFOLDER}/work -ansi-log false

# hopefully success. 
echo "nextflow riboviz ${DATAFOLDER} data run complete"
```

NOTE: this submission script presumes you have the following folder structure & branches for the riboviz and example-datasets both cloned into a folder `$HOME/riboviz`: 
```
# at $HOME: 
mkdir riboviz
cd riboviz
git clone https://github.com/riboviz/example-datasets.git
cd example-datasets
git checkout CryptococcusH99-3

cd .. # back to $HOME/riboviz
git clone https://github.com/riboviz/riboviz.git
cd riboviz
git checkout develop

# want to have this structure:
# $HOME/riboviz/riboviz  # (branch: develop)
# $HOME/riboviz/example-datasets  # (branch: CryptococcusH99-3)
```
I haven't yet set this structure up on the lab group, as it would require us working in separate named folders in there anyway in order to avoid branch requirement issues if more than one person is using Eddie to run something.

**Comment by FlicAnderson** [comment]
> @FlicAnderson can you send me the job submission script so I can try for myself - I'll just look in to JEC21. Then I can accept, add Neurospora #2, and close.
> 
> It looks like I still need to edit the provenance files? Anything else?

Re: the provenance files, yes, those still need doing, I'd forgotten, sorry. But I can't think of anything else?

**Comment by FlicAnderson** [comment]
@ewallace suggested that since riboviz/#220 is blocking running on Eddie, he won't be able to meaningfully try this out, BUT he can update the provenance information. Ditto #4

**Comment by ewallace** [comment]
I am trying this out. I haven't had the job submission script all work at the same time, but the lines in the job submission script all seem to work. I set JEC21 #4 and Neurospora #2 to run on Eddie after validating configurations, and hope to check those results early next week.

Confusion around paths spawned issue #27.

**Comment by ewallace** [comment]
**Reminder: delete duplicate runs on Eddie shared & scratch space before closing this**

**Comment by ewallace** [comment]
I have tested that all these configuration files run on Eddie:
* H99 (closes #3)
* JEC21 (closes #4)
* Neurospora Yu et al (closes #2)

Further, I checked the output was sensible with key diagnostics and 3-nt periodicity. Merging and closing.

**Pull request merged**
