### PR TITLE
Cope homo 93

### PR DESCRIPTION
**Pull request by acope3**
Pull request addressing issue #93

### CODE REVIEW

**Comment by FlicAnderson** [comment]
I've made some tweaks to the config file by running the latest version of upgrade_config over it, removing a few alex-specific path details, and I'm looking forward to testing this in the next few days. 

I've also changed it from 12 to 8 processors, as I'm not sure whether we want this to be so high by default? Hopefully users can crank this up manually if required, but as some folks might run it locally initially, we don't want to put it so high it might kill their system (thoughts?)

**Comment by acope3** [comment]
That’s a good catch. Going forward, I think we should have the number of
processors set to 1 in the config files.

**Comment by FlicAnderson** [comment]
Hoping to run this dataset after I resolve [this git issue](https://github.com/riboviz/example-datasets/pull/64#issuecomment-936352496) I'm having with example datasets on Eddie.

**Comment by FlicAnderson** [comment]
@FlicAnderson aiming to review this on 09th Nov

**Comment by FlicAnderson** [comment]
* I've added environment tokens to the config file (e.g. see run example [here](https://github.com/riboviz/riboviz/blob/main/docs/user/run-env-vars-example.md)) 
* I've run the update config file tool, which has added in a new riboviz `develop` branch feature `hisat2_orf_params` parameter, which I didn't tweak (which is the recommendation [in our config parameter docs](https://github.com/riboviz/riboviz/blob/develop/docs/user/prep-riboviz-config.md))

I've submitted this job to our cluster (job ID: 15567142) & will update with the results once I've got them.

**Comment by FlicAnderson** [comment]
The dataset has completed the run on Eddie: 

Job 15604798 (I-Hs_2019) Complete
 User             = fanders6
 Queue            = eddie@node3g26.ecdf.ed.ac.uk
 Host             = node3g26.ecdf.ed.ac.uk
 Start Time       = 11/15/2021 15:29:52.215
 End Time         = 11/15/2021 16:50:22.616
 User Time        = 05:41:13
 System Time      = 02:01:18
 Wallclock Time   = 01:20:30
 CPU              = 07:42:31
 Max vmem         = 206.472G
 Max rss          = NA
 Exit Status      = 0

Here are the output report: graphs look fairly good to me, can you check this matches what you've got @acope3 ?   

DMSO 1 html report: 
[DMSO_1_output_report.pdf](https://github.com/riboviz/example-datasets/files/7540337/DMSO_1_output_report.pdf)
DMSO 2 html report:
[DMSO_2_output_report.pdf](https://github.com/riboviz/example-datasets/files/7540339/DMSO_2_output_report.pdf) 

Read counts per file. tsv: (saved this as a .csv in order to upload to github...)
[read_counts_per_file.csv](https://github.com/riboviz/example-datasets/files/7540394/read_counts_per_file.csv) 

 
Overall, we've got great 3-nt periodicity, good read lengths, nice clear ribogrid, the position specific distribution of reads seems to match Alex's (mentioned in #93), and the proportion of genes in 1 frame seems great. 

This looks like a really nice clean dataset!

**Comment by ewallace** [comment]
Indeed looks like a nice clean dataset! Clearly many things went right...

**Comment by FlicAnderson** [comment]
I've pushed a couple of extra notes lines to the config about where the environmental tokens used in the yaml ought to point to (to help unfamiliar users) and changed the number of processes to 1 as discussed w/ @acope3. 

I think this should be ready to merge and close.

**Review by FlicAnderson — APPROVED** [review]

**Comment by FlicAnderson** [comment]
(merged in 'main' branch to check for conflicts, none found, good to merge `cope-homo-93` to `main`)

**Comment by FlicAnderson** [comment]
Merged & closing, deleting branch.

**Pull request merged**
