### PR TITLE
Add config.yaml for Zou et al 2020 to example-datasets/fungi/saccharomyces

### PR DESCRIPTION
**Pull request by swinterbourne**
Add Zou_2020_Glucose-restricted_RPF_6-samples-CDS_w_250utrs_config.yaml to example-datasets/fungi/saccharomyces. Related to issue #61

### CODE REVIEW

**Comment by FlicAnderson** [comment]
I haven't run this yet either, but I think it's worth doing the same steps as I mentioned for the L-Sc_2014 dataset - [edit `dir` path](https://github.com/riboviz/example-datasets/pull/65#pullrequestreview-599524363) and [add the config yaml to the README](https://github.com/riboviz/example-datasets/pull/65#issuecomment-786615912)

**Comment by FlicAnderson** [comment]
I've merged `master` into this branch as it's been a while since this was created & I wanted to avoid any potential conflicts.

**Comment by FlicAnderson** [comment]
I was trying to set up this dataset to run, but I've run into errors:

 `Cannot parse params file: Z-Sc_2020/Zou_2020_Glucose-restricted_RPF_6-samples-CDS_w_250utrs_config.yaml`

These fail the whole job, and I think it's related to some of the new code that's merged into the `rmarkdown-outputs-193` branch I was trying to run it with.  

I don't think I've updated the config file correctly with the new parameters, and also the usual home-brewed job submission script I used to use is probably defunct and I should be using a job submission script generated by riboviz? 

I'm leaving this parked for tonight so I can work on other things but will try and pick it up tomorrow.

**Comment by FlicAnderson** [comment]
I think a rouge `:` might have been partially to blame for my "cannot parse params file" error. I tried using `upgrade_config_file` script to add the new parameters required, but ran into an error: 
```
yaml.scanner.ScannerError: mapping values are not allowed here
  in "Zou_2020_Glucose-restricted_RPF_6-samples-CDS_w_250utrs_config.yaml", line 11, column 99
```  
This error gave me the clue - it seems like the ':' in the `reference:` text entry was causing things to presume there was another nested parameter. I changed it out for a dash and the update script worked fine, and I've then updated the Zou et al config file with these new parameters, slightly edited from the job info defaults to match the memory / processor values I'm requesting on runs now. 

These edits seemed to let the dataset run after job submission, although I did need to use `-work-dir` parameter in the nextflow run command as my entry in the config file for setting work directory location (I used `nextflow_work_dir: Z-Sc_2020/work`) didn't do anything & it ended it up throwing it into my Eddie home dir which caused the run to fail as it ran into the quota limit and the system fell over. Overwriting it with the equivalent location using `-work-dir` in my job submission script seemed to work fine.  

The dataset is currently running on Eddie, will update with results when it completes.

**Comment by FlicAnderson** [comment]
Ugh. Job aborted due to lack of memory, despite being given 200GB. 

```
Job 11546213 (Z-Sc_2020) Aborted
 Exit Status      = 137
 Signal           = KILL
 User             = fanders6
 Queue            = eddie@node3g10.ecdf.ed.ac.uk
 Host             = node3g10.ecdf.ed.ac.uk
 Start Time       = 05/05/2021 14:09:09.293
 End Time         = 05/05/2021 15:56:45.791
 CPU              = 17:00:13
 Max vmem         = 201.856G
 Max rss          = NA
failed execd enforced h_vmem limit because:
job 11546213.1 died through signal KILL (9)
``` 

I'll try re-running this with 240GB next time and it should hopefully pass fine. Will try and remember to do '-resume' this time to check outputs, but it really would be good to know how long the run takes in one go as well.

**Comment by FlicAnderson** [comment]
It failed during the generateStatsFigs processes, which I think is usual for when it runs out of memory... 

I've resubmitted with `sharedmem 12` and `h_vmem=20G` (240GB), which ought to suffice; decided against `-resume` as I want to see if it has the same problems in the same place and get overall dataset run info from the job. 

Currently running.

**Comment by kavousan** [comment]
> I've resubmitted with `sharedmem 12` and `h_vmem=20G` (240GB), which ought to suffice

I did not follow back then, but I am tempted to have another go: do you have the instructions/explanations handy so I can see what (if anything) I can figure out?

**Comment by FlicAnderson** [comment]
@kavousan - here are the Eddie memory specification help pages: https://www.wiki.ed.ac.uk/display/ResearchServices/Memory+Specification#MemorySpecification-Estimatingmemoryrequirements 

According to advice Angela from the Eddie team gave here: https://github.com/riboviz/riboviz/issues/236#issuecomment-819609764 
I had previously been trying to give an overall limit of 180GB (20GB per each of 9 cores), but this seemed to be insufficient when I ran #48 and so for this dataset I tried starting off with 200GB (10 cores via the sharedmem parallel environment, 20GB each, total of 200GB). 

I submitted the job with those specs, and it ran for a few hours. 

The job was then aborted by the scheduling system and the system these details about the job: 
```
[fanders6@login01(eddie) ~]$ qacct -j 11546213
==============================================================
qname        eddie               
hostname     node3g10.ecdf.ed.ac.uk
group        eddie_users         
owner        fanders6            
project      bio_wallace_rna_riboviz
department   defaultdepartment   
jobname      Z-Sc_2020           
jobnumber    11546213            
taskid       undefined
pe_taskid    NONE                
account      sge                 
priority     0                   
cwd          /home/fanders6      
submit_host  login02.ecdf.ed.ac.uk
submit_cmd   qsub LogfileStargate/run_Z-Sc_2020.sh
qsub_time    05/05/2021 14:08:26.527
start_time   05/05/2021 14:09:09.293
end_time     05/05/2021 15:56:45.791
granted_pe   sharedmem           
slots        10                  
failed       46  : execd enforced h_vmem limit
deleted_by   NONE
exit_status  137                 
ru_wallclock 6456.498     
ru_utime     11.006       
ru_stime     1.185        
ru_maxrss    347660              
ru_ixrss     0                   
ru_ismrss    0                   
ru_idrss     0                   
ru_isrss     0                   
ru_minflt    257929              
ru_majflt    0                   
ru_nswap     0                   
ru_inblock   0                   
ru_oublock   1928                
ru_msgsnd    0                   
ru_msgrcv    0                   
ru_nsignals  0                   
ru_nvcsw     17862               
ru_nivcsw    272                 
wallclock    6457.242     
cpu          61213.330    
mem          76605.024         
io           4674.224          
iow          0.000             
ioops        375655005           
maxvmem      201.856G
maxrss       0.000
maxpss       0.000
arid         undefined
jc_name      NONE
bound_cores  0,0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9
```
The key parts I think are: 
`failed       46  : execd enforced h_vmem limit` and `maxvmem 201.856G`. 

Since I requested 200GB of resources, the scheduler kills the job when it exceeds this 200GB limit (ie it reached 201.856GB).  

I'm presuming it was the generateStatsFigs process that was the final straw in terms of resources, as that's the stage the nextflow job had reached according to the job output:
```
# from the job output file: 
[fanders6@login01(eddie) ~]$ cat Z-Sc_2020-11546213-node3g10.ecdf.ed.ac.uk.o
Running riboviz on dataset: Z-Sc_2020
now in folder: /home/fanders6/riboviz/riboviz ready to run
N E X T F L O W  ~  version 20.04.1
Launching `prep_riboviz.nf` [hopeful_spence] - revision: 70a12ece9f
Validating configuration only
Validated configuration
N E X T F L O W  ~  version 20.04.1
Launching `prep_riboviz.nf` [exotic_brattain] - revision: 70a12ece9f
[6e/a6b060] Submitted process > cutAdapters (GR-sample4-2)
[bf/e98169] Submitted process > buildIndicesrRNA (yeast_rRNA)
[2b/a8cd5f] Submitted process > cutAdapters (SD-sample7)
[fc/9075d7] Submitted process > cutAdapters (GR-sample8)
[b3/61e162] Submitted process > cutAdapters (SD-sample3-1)
[1f/f7328b] Submitted process > cutAdapters (GR-sample4-1)
[3d/e00153] Submitted process > cutAdapters (SD-sample3-2)
[f3/9bd682] Submitted process > buildIndicesORF (yeast_CDS_w_250)
[2a/fff257] Submitted process > createConfigFile
[48/ff23bc] Submitted process > hisat2rRNA (GR-sample4-1)
[7b/75767b] Submitted process > hisat2rRNA (SD-sample3-1)
[42/3dcd7b] Submitted process > hisat2rRNA (SD-sample7)
[07/7e0b6e] Submitted process > hisat2rRNA (GR-sample8)
[72/616183] Submitted process > hisat2rRNA (GR-sample4-2)
[b5/60fa7a] Submitted process > hisat2rRNA (SD-sample3-2)
[7f/bae88f] Submitted process > hisat2ORF (GR-sample4-1)
[6a/54240f] Submitted process > trim5pMismatches (GR-sample4-1)
[6d/37ab7f] Submitted process > samViewSort (GR-sample4-1)
[fb/f6fece] Submitted process > outputBams (GR-sample4-1)
[c0/d73a62] Submitted process > bamToH5 (GR-sample4-1)
[fd/2bfb83] Submitted process > makeBedgraphs (GR-sample4-1)
[ee/42e4a7] Submitted process > hisat2ORF (SD-sample3-1)
[63/30c74d] Submitted process > hisat2ORF (SD-sample7)
[89/b1a200] Submitted process > hisat2ORF (GR-sample8)
[14/66c60a] Submitted process > hisat2ORF (GR-sample4-2)
[58/d892f7] Submitted process > trim5pMismatches (SD-sample3-1)
[ec/cdbc05] Submitted process > trim5pMismatches (SD-sample7)
[ca/6fdaf4] Submitted process > generateStatsFigs (GR-sample4-1)
[2b/7710d8] Submitted process > trim5pMismatches (GR-sample4-2)
[bb/8a691d] Submitted process > trim5pMismatches (GR-sample8)
[1e/465ec3] Submitted process > samViewSort (SD-sample3-1)
[5a/869787] Submitted process > samViewSort (SD-sample7)
[42/adc5a2] Submitted process > hisat2ORF (SD-sample3-2)
[86/2391f2] Submitted process > samViewSort (GR-sample4-2)
[f2/b7fa62] Submitted process > outputBams (GR-sample4-2)
[4f/29c1f0] Submitted process > bamToH5 (GR-sample4-2)
[1a/deb1d8] Submitted process > makeBedgraphs (GR-sample4-2)
[8d/2bc02a] Submitted process > outputBams (SD-sample3-1)
[62/1e770d] Submitted process > bamToH5 (SD-sample3-1)
[b7/95899b] Submitted process > makeBedgraphs (SD-sample3-1)
[4c/fcca3b] Submitted process > outputBams (SD-sample7)
[f2/0422ba] Submitted process > samViewSort (GR-sample8)
[58/fb7cee] Submitted process > makeBedgraphs (SD-sample7)
[c5/9693f5] Submitted process > bamToH5 (SD-sample7)
[3e/3c2427] Submitted process > trim5pMismatches (SD-sample3-2)
[60/4bfa7c] Submitted process > outputBams (GR-sample8)
[57/0e0a1b] Submitted process > makeBedgraphs (GR-sample8)
[75/5035d5] Submitted process > bamToH5 (GR-sample8)
[d4/5cffd1] Submitted process > generateStatsFigs (GR-sample4-2)
[a4/7d2178] Submitted process > generateStatsFigs (SD-sample7)
[aa/4a2267] Submitted process > generateStatsFigs (SD-sample3-1)
[b0/6ff419] Submitted process > samViewSort (SD-sample3-2)
[b2/a6a2d9] Submitted process > outputBams (SD-sample3-2)
[f7/60a24f] Submitted process > bamToH5 (SD-sample3-2)
[98/ac4d40] Submitted process > makeBedgraphs (SD-sample3-2)
[5b/dd1d98] Submitted process > generateStatsFigs (GR-sample8)
[7e/3f4e49] Submitted process > generateStatsFigs (SD-sample3-2)
```

Unfortunately I can't check further into the work directory files as I deleted them before I re-ran the job (which was unwise, because now I can't dig further into what was going on when the job got killed). 

Does this make any sense? 

The Kasari et al (#48) dataset is the one I mentioned in the call.  On the Kasari et al run, I'd set the initial limit to 180GB (e.g. 9 cores w/ 20GB each) and received: 
```
Job 11389845 (K-Sc-eEF3_2019) 
Aborted Exit Status = 137  
Signal = KILL User = fanders6  
Queue = eddie@node3g10.ecdf.ed.ac.uk  
Host = node3g10.ecdf.ed.ac.uk  
Start Time = 04/21/2021 14:47:30.999  
End Time = 04/21/2021 20:38:55.150  
CPU = 2:01:37:00  
Max vmem = 181.017G  
Max rss = NA failed execd enforced h_vmem limit  because: job 11389845.1 died through signal KILL (9)
```
So it had hit 181GB, exceeded the request allocation limits I'd set when submitting the job, and the scheduler killed it. 

But when I resubmitted the same job (Kasari et al) requesting 12 cores at 20GB this time (total of 240GB):
```
Job 11399859 (K-Sc-eEF3_2019) 
Complete User = fanders6  
Queue = eddie@node3g10.ecdf.ed.ac.uk  
Host = node3g10.ecdf.ed.ac.uk  
Start Time = 04/22/2021 12:03:43.859  
End Time = 04/23/2021 00:38:42.915  
User Time = 1:21:08:11  
System Time = 1:07:14:23  
Wallclock Time = 12:34:59  
CPU = 3:04:22:35  
Max vmem = 170.847G  
Max rss = NA  
Exit Status = 0
```
 It completed running fine, all well, but you can see `Max vmem` only reached 170.847G, and so didn't hit 181.017G, which was the limit it hit before it was killed on the previous attempt to run the same dataset in the same way. 

I don't understand quite why it didn't reach 181GB the second time I ran it (with more headroom).

**Comment by FlicAnderson** [comment]
I still haven't attempted to run this lately, and I believe it probably needs to be run through the config upgrade script since it's been sitting dormant for a little while, waiting for me to review it. I'll try and get to this in the next day or two.

**Comment by FlicAnderson** [comment]
Merged in latest main, & used the upgrade config tool from develop branch to upgrade it, then shoogled around some of the non-alphabetic new parameters into the correct places. I think this should be run before merging & closing, but this will then wrap up #61 finally. 

Next step is for #92  to remove non-2.1 config yamls, and rename 2.1 config yamls, then complete #71.

**Comment by mikej888** [comment]
@FlicAnderson sorry, no, that's new to me. I'm surprised you get it with a fresh clone. It's maybe the way the host filesystem is configured to deny `group` or `other` execute access. In my VM clone of `example-datasets` those files are executable also. As they're data files and no reason for them to be executable one workaround would be to commit the modifications to `example-datasets`.

**Comment by FlicAnderson** [comment]
Setting this dataset up to run and check next now #96 is completed. Need to upgrade config and include environment tokens to match other datasets (in progress).

**Comment by FlicAnderson** [comment]
Re-downloading fastq files for dataset as previously these had been in scratch and were deleted some time ago, **currently awaiting SRA downloading script to run and complete** (using `fasterq-dump` from SRAtoolkit), before I can submit the main job. 

I've upgraded the config file to the latest version, so this will be riboviz 2.1 compatible, and added environment tokens and link/notes on how to use them for running this config.

**Comment by FlicAnderson** [comment]
This dataset was run and completed successfully: 
```
Job 15638613 (Z-Sc_2020) Complete
 User             = fanders6
 Queue            = eddie@tc02.ecdf.ed.ac.uk
 Host             = tc02.ecdf.ed.ac.uk
 Start Time       = 11/17/2021 22:49:21.249
 End Time         = 11/18/2021 09:05:52.806
 User Time        = 2:13:18:06
 System Time      = 1:13:47:44
 Wallclock Time   = 10:16:31
 CPU              = 4:03:05:51
 Max vmem         = 192.425G
 Max rss          = NA
 Exit Status      = 0
```

It was submitted with the following yaml content:
```
cat Zou_2020_Glucose-restricted_RPF_6-samples-CDS_w_250utrs_config.yaml 
provenance:
  yaml authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author: Sophie Winterbourne
  DOI: http://dx.doi.org/10.1126/sciadv.aba1306
  GEO: GSE134152
  date run: 2021-11-17
  notes: Ribosome profiling datasets of Saccharomyces cerevisiae grown under glucose
    restriction conditions.
  reference: Life span extension by glucose restriction is abrogated by methionine
    supplementation - Cross-talk between glucose and methionine and implication of
    methionine as a key regulator of life span, Zou et al 2020.
  riboviz-version: 2.1 | COMMIT ac84378a460378eb0458c81f5bfffc6f2be24fac
  riboviz environment tokens use: for advice on how to use environment tokens with riboviz, see documentation at https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-config.md#environment-variables-and-configuration-tokens
  riboviz environment tokens note 1: ${RIBOVIZ_DATA} should point to riboviz repo data folder location e.g. /home/user/riboviz/riboviz/data
  riboviz environment tokens note 2: ${RIBOVIZ_ORGANISMS} is location of example-datasets Saccharomyces genus data repository folder e.g. /home/user/riboviz/example-datasets/fungi/saccharomyces
  riboviz environment tokens note 3: ${RIBOVIZ_SAMPLES} should point to location where input data fastq file has been downloaded & placed within 'input' folder e.g. /home/user/Z-Sc_2020

adapters: CTGTAGGCACCATCAAT
asite_disp_length_file: ${RIBOVIZ_DATA}/yeast_standard_asite_disp_length.txt
buffer: 250
build_indices: true
codon_positions_file: ${RIBOVIZ_DATA}/yeast_codon_pos_i200.RData
count_reads: true
count_threshold: 64
dataset: Z-Sc_2020
dedup_stats: false
dedup_umis: false
dir_in: ${RIBOVIZ_SAMPLES}/input
dir_index: ${RIBOVIZ_SAMPLES}/index
dir_out: ${RIBOVIZ_SAMPLES}/output
dir_tmp: ${RIBOVIZ_SAMPLES}/tmp
extract_umis: false
feature: CDS
features_file: ${RIBOVIZ_DATA}/yeast_features.tsv
fq_files:
  SD-sample3-1: SRR9670816.fastq.gz
  SD-sample3-2: SRR9670817.fastq.gz
  GR-sample4-1: SRR9670818.fastq.gz
  GR-sample4-2: SRR9670819.fastq.gz
  SD-sample7: SRR9670822.fastq.gz
  GR-sample8: SRR9670823.fastq.gz
group_umis: false
hisat2_orf_params: -k 2 --no-spliced-alignment --rna-strandness F --no-unal
is_riboviz_gff: true
job_email: [REMOVED MY EMAIL]
job_email_events: beas
job_memory: 20G
job_name: Z-Sc_2020
job_num_cpus: 12
job_parallel_env: sharedmem
job_runtime: '24:00:00'
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: Z-Sc_2020/work
num_processes: 12
orf_fasta_file: ${RIBOVIZ_ORGANISMS}/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa
orf_gff_file: ${RIBOVIZ_ORGANISMS}/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3
orf_index_prefix: yeast_CDS_w_250
output_metagene_normalized_profile: true
output_pdfs: true
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ${RIBOVIZ_ORGANISMS}/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa
rrna_index_prefix: yeast_rRNA
run_static_html: true
sample_sheet: null
samsort_memory: null
secondary_id: null
skip_inputs: false
stop_in_feature: false
t_rna_file: ${RIBOVIZ_DATA}/yeast_tRNAs.tsv
trim_5p_mismatches: true
umi_regexp: null
validate_only: false
``` 
NOTE: This yaml differs from example-datasets branch version yaml in requesting resources suitable for the Eddie compute cluster therefore has different values for: `job_memory`: 20G, `job_num_cpus`: 12, `job_parallel_env`: sharedmem and `job_runtime`: '24:00:00'. `num_processes` has been set to 12 to match `job_num_cpus`. 

This requested 12 * 20G of memory (240GB), but as the job maximum was close to 200GB, this seemed to work fine and gave sufficient headroom for the processes to run to completion. 

This dataset was run with files from `example-datasets` branch `Zou-Sc-2020-config-61` (last commit a4dfdfbb, but with yaml edited as mentioned above in this ticket) through `riboviz` `develop` branch (last commit  ac84378a4603). 

The html reports generated are as follows: 
[GR-sample4-1_output_report.pdf](https://github.com/riboviz/example-datasets/files/7634205/GR-sample4-1_output_report.pdf)
[GR-sample4-2_output_report.pdf](https://github.com/riboviz/example-datasets/files/7634207/GR-sample4-2_output_report.pdf)
[GR-sample8_output_report.pdf](https://github.com/riboviz/example-datasets/files/7634208/GR-sample8_output_report.pdf)
[SD-sample3-1_output_report.pdf](https://github.com/riboviz/example-datasets/files/7634209/SD-sample3-1_output_report.pdf)
[SD-sample3-2_output_report.pdf](https://github.com/riboviz/example-datasets/files/7634210/SD-sample3-2_output_report.pdf)
[SD-sample7_output_report.pdf](https://github.com/riboviz/example-datasets/files/7634211/SD-sample7_output_report.pdf)

The results for sample SD-sample3-1 match those found [previously by Sophie](https://github.com/riboviz/example-datasets/issues/61#issuecomment-785158307), and generally most samples show excellent periodicity and high proportion of reads in 1 frame.  

Samples `SD-sample3-1` and sample `SD-sample7` are slightly odd and the more equal frame proportions and periodicity graphs show that there's perhaps something a little strange going on there, but as the former sample replicates Sophie's previous results, and the dataset runs, I'm tempted to mark this dataset ready to merge, as it does generate results which can be compared and investigated.

**Pull request merged**
