### PR TITLE
Add config.yaml for Lareau et al 2014 to example-datasets/fungi/saccharomyces

### PR DESCRIPTION
**Pull request by swinterbourne**
Add Lareau_2014_Replicates_RPF_3-samples_CDS_w_250utrs_config.yaml to example-datasets/fungi/saccharomyces. Linked to issue #58.

### CODE REVIEW

**Review by FlicAnderson — COMMENTED** [review]
Hiya, I haven't had a chance to run this yet, but:

With the `dir_*` parameters, I think it's worth removing the `../` beforehand to match the format with the other datasets.  

Usually, the linked dataset folder is INSIDE the riboviz folder:
```
/home/$USER/riboviz/riboviz/L-Sc_2014
```
I think for now it would be best to replicate that structure to keep all the datasets consistent?

So your YAML dir_in would read: `dir_in: L-Sc_2014/input`.

This would also mean creating the sym-linked folder once you're inside the main riboviz folder:
```
# move into riboviz folder
cd $HOME/riboviz/riboviz

# make system link at riboviz folder to folder on scratch
ln -s /exports/eddie/scratch/$USER/$DATAFOLDER
```
So that the datafolder (L-Sc_2014) points to the right scratch location, but is consistent with other dataset structures.

Once we've got the path variables stuff sorted out on some other tickets, this might become less of an issue, but for now I think it's good to do it this way.

**Comment by FlicAnderson** [comment]
Also worth editing `/fungi/README.md` to add this yaml config file to the Saccaromyces cerevisiae section as we want to add that info for each new dataset

**Comment by ewallace** [comment]
I suggest trying to run this using the python job submission script documented in [riboviz/docs/user/create-job-script.md](https://github.com/riboviz/riboviz/blob/develop/docs/user/create-job-script.md), then updating issue ticket [riboviz#289](riboviz/riboviz/issues/289).

**Comment by ewallace** [comment]
@swinterbourne I would like to try and test this - are the .fastq.gz files on a shared space accesible to me on Eddie or need I re-download?

**Comment by swinterbourne** [comment]
You will need to re-download them. Everything was in scratch which I removed due to space issues.

**Comment by FlicAnderson** [comment]
@swinterbourne I'm currently running this (with all 3 samples) on Eddie to test; so far, so good.

**Comment by ewallace** [comment]
@FlicAnderson this is great news - can you run a version through the .html output too?

**Comment by FlicAnderson** [comment]
Successfully run this using `develop` and `rmarkdown-outputs-193` branches of riboviz on Eddie.

**Comment by ewallace** [comment]
Merge it!

**Pull request merged**
